In [1]:
import pandas as pd
from sqlalchemy import create_engine
import os

db_string = 'mysql+pymysql://root:!wMoU9lBdLZWW6Y8@o8ukkP9TliImN.h.filess.io:58202/MLS'

engine = create_engine(db_string)

In [2]:
df = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim//cleaned_master_players_w_team_abbr_post031426.csv')

In [3]:
df2 = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/players/cleaned_master_players_w_team_abbr_post031426_2.csv')

In [4]:
## rename id to player_id

df.rename(columns={'id': 'player_id'}, inplace=True)

In [5]:
df

,player_id,date,name,age,height_cm,weight_kg,team_name,contract_start,contract_end,position,...,defensive_awareness,standing_tackle,sliding_tackle,total_goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,team_abbr
0,247228,2026-03-10,D. St. Clair,28,191,86,Inter Miami,NaN,NaN,NaN,...,8.0,10.0,12.0,350,73.0,69.0,60.0,72.0,76.0,MIA
1,262339,2026-03-10,G. Lujan,24,182,82,Inter Miami,NaN,NaN,NaN,...,67.0,69.0,68.0,43,10.0,9.0,5.0,9.0,10.0,MIA
2,259298,2026-03-10,M. Falcon,28,179,80,Inter Miami,NaN,NaN,NaN,...,62.0,67.0,64.0,52,7.0,11.0,15.0,11.0,8.0,MIA
3,260732,2026-03-10,I. Fray,22,183,73,Inter Miami,NaN,NaN,NaN,...,66.0,67.0,63.0,57,13.0,10.0,6.0,15.0,13.0,MIA
4,267872,2026-03-10,N. Allen,21,175,66,Inter Miami,NaN,NaN,NaN,...,64.0,68.0,66.0,52,11.0,13.0,9.0,8.0,11.0,MIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2135,80612,2026-02-18,P. Soma,19,177,75,San Diego FC,NaN,NaN,NaN,...,48.0,45.0,52.0,44,11.0,6.0,6.0,11.0,10.0,SD
2136,70074,2026-02-18,K. Sargeant,22,182,73,San Diego FC,NaN,NaN,NaN,...,40.0,50.0,51.0,64,13.0,10.0,14.0,13.0,14.0,SD
2137,77459,2026-02-18,A. Saidi,17,185,67,San Diego FC,NaN,NaN,NaN,...,18.0,12.0,17.0,57,8.0,14.0,11.0,9.0,15.0,SD
2138,73870,2026-02-18,D. Vazquez,19,175,65,San Diego FC,NaN,NaN,NaN,...,21.0,20.0,24.0,49,14.0,10.0,6.0,10.0,9.0,SD
2139,255411,2026-02-18,B. Duke,24,170,66,San Diego FC,NaN,NaN,NaN,...,49.0,50.0,41.0,44,6.0,8.0,12.0,8.0,10.0,SD

In [6]:
##3 keep player_id, name, height, and foot

df = df[['player_id', 'name', 'height_cm', 'foot']]

In [7]:
df

      player_id          name  height_cm   foot
0        247228  D. St. Clair        191   Left
1        262339      G. Lujan        182  Right
2        259298     M. Falcon        179  Right
3        260732       I. Fray        183  Right
4        267872      N. Allen        175   Left
...         ...           ...        ...    ...
2135      80612       P. Soma        177  Right
2136      70074   K. Sargeant        182  Right
2137      77459      A. Saidi        185  Right
2138      73870    D. Vazquez        175   Left
2139     255411       B. Duke        170  Right

[2140 rows x 4 columns]

In [8]:
### keep only one entry per player_id

df = df.drop_duplicates(subset=['player_id'])

In [ ]:
df

      player_id          name  height_cm   foot
0        247228  D. St. Clair        191   Left
1        262339      G. Lujan        182  Right
2        259298     M. Falcon        179  Right
3        260732       I. Fray        183  Right
4        267872      N. Allen        175   Left
...         ...           ...        ...    ...
2080      77459      A. Saidi        185  Right
2081      73870    D. Vazquez        175   Left
2082     255411       B. Duke        170  Right
2083      79998     W. Eisner        183  Right
2093     260482      T. Angel        175   Left

[799 rows x 4 columns]

In [15]:
from sqlalchemy import inspect

inspector = inspect(engine)
print(inspector.get_table_names())  # Lists all tables in the default schema
print(inspector.has_table("players_general"))

['match_events', 'match_player_stats', 'match_team_stats', 'matches', 'player_finance', 'players_finance', 'players_general', 'players_general_name_stage', 'players_stats', 'roster_snapshots', 'team_roster', 'team_roster_stage', 'team_stats', 'teams']
True

In [54]:
from sqlalchemy import Table, MetaData, insert

metadata = MetaData()
metadata.reflect(bind=engine)

# Access any table like a dictionary
players_table = metadata.tables['players_general']

stmt = insert(players_table).prefix_with("IGNORE").values(df)

KeyboardInterrupt:

In [10]:
## save to sql

df.to_sql('players_general', con=engine, if_exists='append', index=False)

3911

In [3]:
old1 = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/master_players_w_team_abbr.csv')
old2 = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/master_players_w_team_abbr_post021026.csv')
old3 = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/cleaned_master_players_w_team_abbr_post031426.csv')

In [5]:
master = pd.concat([old1, old2, old3], ignore_index=True)

In [10]:
master

,id,date,name,age,height_cm,weight_kg,team,contract_start,contract_end,position,...,gk_handling,gk_kicking,gk_positioning,gk_reflexes,marking,tactical_awareness,positioning,tackling,team_abbr,team_name
0,238919,2023-01-18,J. Pantemis,25.0,188,79,MTL,2018.0,2023.0,GK,...,63.0,54.0,66.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN
1,255956,2023-01-18,J. Waterman,26.0,185,75,MTL,2020.0,2023.0,RCB,...,7.0,10.0,11.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN
2,206485,2023-01-18,R. Camacho,31.0,185,79,MTL,2022.0,2023.0,CB,...,6.0,6.0,15.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN
3,247648,2023-01-18,K. Miller,25.0,183,88,MTL,2021.0,2023.0,LCB,...,11.0,12.0,7.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN
4,243574,2023-01-18,Z. Brault-Guillard,23.0,171,65,MTL,2020.0,2022.0,RM,...,6.0,11.0,11.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1942471,80612,2026-02-18,P. Soma,19.0,177,75,NaN,NaN,NaN,NaN,...,6.0,6.0,11.0,10.0,NaN,NaN,NaN,NaN,SD,San Diego FC
1942472,70074,2026-02-18,K. Sargeant,22.0,182,73,NaN,NaN,NaN,NaN,...,10.0,14.0,13.0,14.0,NaN,NaN,NaN,NaN,SD,San Diego FC
1942473,77459,2026-02-18,A. Saidi,17.0,185,67,NaN,NaN,NaN,NaN,...,14.0,11.0,9.0,15.0,NaN,NaN,NaN,NaN,SD,San Diego FC
1942474,73870,2026-02-18,D. Vazquez,19.0,175,65,NaN,NaN,NaN,NaN,...,10.0,6.0,10.0,9.0,NaN,NaN,NaN,NaN,SD,San Diego FC
1942475,255411,2026-02-18,B. Duke,24.0,170,66,NaN,NaN,NaN,NaN,...,8.0,12.0,8.0,10.0,NaN,NaN,NaN,NaN,SD,San Diego FC

In [16]:
master.to_csv('G:/My Drive/GitHubProjects/MLS/data/interim/cleaned_master_players_w_team_abbr_post031426_2.csv', index=False)

In [55]:
df2.head()

,id,date,name,age,height_cm,weight_kg,team_name,contract_start,contract_end,position,...,defensive_awareness,standing_tackle,sliding_tackle,total_goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,team_abbr
0,238919,2023-01-18,J. Pantemis,25.0,188,79,CF Montréal,2018.0,2023.0,GK,...,8.0,12.0,14,315,66,63,54,66,66,MTL
1,255956,2023-01-18,J. Waterman,26.0,185,75,CF Montréal,2020.0,2023.0,RCB,...,68.0,68.0,62,45,6,7,10,11,11,MTL
2,206485,2023-01-18,R. Camacho,31.0,185,79,CF Montréal,2022.0,2023.0,CB,...,69.0,66.0,65,49,8,6,6,15,14,MTL
3,247648,2023-01-18,K. Miller,25.0,183,88,CF Montréal,2021.0,2023.0,LCB,...,69.0,69.0,73,50,8,11,12,7,12,MTL
4,243574,2023-01-18,Z. Brault-Guillard,23.0,171,65,CF Montréal,2020.0,2022.0,RM,...,61.0,64.0,60,50,11,6,11,11,11,MTL

In [56]:
unique_df = df2.drop_duplicates(subset=['id'], keep='first')

In [57]:
unique_df

,id,date,name,age,height_cm,weight_kg,team_name,contract_start,contract_end,position,...,defensive_awareness,standing_tackle,sliding_tackle,total_goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,team_abbr
0,238919,2023-01-18,J. Pantemis,25.0,188,79,CF Montréal,2018.0,2023.0,GK,...,8.0,12.0,14,315,66,63,54,66,66,MTL
1,255956,2023-01-18,J. Waterman,26.0,185,75,CF Montréal,2020.0,2023.0,RCB,...,68.0,68.0,62,45,6,7,10,11,11,MTL
2,206485,2023-01-18,R. Camacho,31.0,185,79,CF Montréal,2022.0,2023.0,CB,...,69.0,66.0,65,49,8,6,6,15,14,MTL
3,247648,2023-01-18,K. Miller,25.0,183,88,CF Montréal,2021.0,2023.0,LCB,...,69.0,69.0,73,50,8,11,12,7,12,MTL
4,243574,2023-01-18,Z. Brault-Guillard,23.0,171,65,CF Montréal,2020.0,2022.0,RM,...,61.0,64.0,60,50,11,6,11,11,11,MTL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454472,83296,2026-02-05,N. Markovic,20.0,193,93,DC United,NaN,NaN,NaN,...,55.0,55.0,55,53,11,14,5,11,12,DC
1454715,82879,2026-02-05,C. Flax,21.0,180,68,New York City FC,NaN,NaN,NaN,...,30.0,35.0,46,59,10,9,15,11,14,NYC
1454716,82889,2026-02-05,K. Acito,21.0,190,84,New York City FC,NaN,NaN,NaN,...,58.0,53.0,52,51,7,15,8,12,9,NYC
1455539,279938,2026-02-05,S. Jura,19.0,172,69,Portland Timbers,NaN,NaN,NaN,...,41.0,45.0,43,57,15,9,10,10,13,POR
1456205,73878,2026-02-05,C. Cowell,16.0,170,71,Real Salt Lake,NaN,NaN,NaN,...,26.0,25.0,24,48,13,11,7,8,9,RSL

In [58]:
### find ids not in players_general

players_general = pd.read_sql("SELECT * FROM players_general", con=engine)

ids_not_in_general = unique_df[~unique_df['id'].isin(players_general['player_id'])]

ids_not_in_general

Empty DataFrame
Columns: [id, date, name, age, height_cm, weight_kg, team_name, contract_start, contract_end, position, foot, jersey_num, wage_eur, value_eur, overall_rating, best_overall, best_position, total_attacking, crossing, finishing, heading_accuracy, short_passing, volleys, total_skill, dribbling, curve, fk_accuracy, long_passing, ball_control, total_movement, acceleration, sprint_speed, agility, reactions, balance, total_power, shot_power, jumping, stamina, long_shots, total_mentality, aggression, interceptions, attack_position, vision, penalties, composure, total_defending, defensive_awareness, standing_tackle, sliding_tackle, total_goalkeeping, gk_diving, gk_handling, gk_kicking, gk_positioning, gk_reflexes, team_abbr]
Index: []

[0 rows x 58 columns]

In [18]:
master = master[['id', 'name', 'height_cm', 'foot']]

In [59]:
### find nan values in master

nan_values = master[master.isna().any(axis=1)]

nan_values

Empty DataFrame
Columns: [id, name, height_cm, foot]
Index: []

In [22]:
### fill id 220575 with Victor Pagliari Giro

master.loc[master['id'] == 220575, 'name'] = 'Victor Pagliari Giro'

In [33]:
### find na values in master

nan_values = master[master.isna().any(axis=1)]

nan_values

Empty DataFrame
Columns: [id, name, height_cm, foot]
Index: []

In [32]:
from sqlalchemy import create_engine, Table, MetaData, insert

# 1. Define your table (must match your DB structure)
metadata = MetaData()
players_table = Table("players_general", metadata, autoload_with=engine) # or define Columns manually

# 2. Convert DataFrame to a list of dicts
data = master.to_dict(orient="records")

# 3. Build and execute the statement
stmt = insert(players_table).prefix_with("IGNORE")

with engine.connect() as conn:
    conn.execute(stmt, data) # Pass data as the second argument
    conn.commit()

C:\Users\diffe\AppData\Local\Temp\ipykernel_16048\753919839.py:14: SAWarning: Column 'players_general.player_id' is marked as a member of the primary key for table 'players_general', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL.
  conn.execute(stmt, data) # Pass data as the second argument

In [30]:
with engine.connect() as conn:
    conn.commit()

In [60]:
### compare db and master dataframes for ids not in other

mysql_values = set(pd.read_sql("SELECT player_id FROM players_general", engine)["player_id"])
df_values    = set(master["id"])
old_values   = set(df2["id"])

in_mysql_not_df = mysql_values - df_values
in_df_not_mysql = df_values - mysql_values
in_old_not_new = old_values - df_values
in_new_not_old = df_values - old_values
in_sql_not_old = mysql_values - old_values
in_old_not_sql = old_values - mysql_values

In [61]:
print(f"Original length: {len(master)}")
print(f"Unique length: {len(unique_df)}")
print(f"Length of older master DataFrame: {len(df2)}")
print(f"IDs in MySQL not in DataFrame: {in_mysql_not_df}")
print(f"IDs in DataFrame not in MySQL: {in_df_not_mysql}")
print(f"IDs in older master DataFrame not in new DataFrame: {in_old_not_new}")
print(f"IDs in new DataFrame not in older master DataFrame: {in_new_not_old}") 
print(f"IDs in MySQL not in DataFrame: {in_sql_not_old}")
print(f"IDs in DataFrame not in MySQL: {in_old_not_sql}")
print(f"number of ids in MySQL not in DataFrame: {len(in_mysql_not_df)}")
print(f"number of ids in DataFrame not in MySQL: {len(in_df_not_mysql)}")
print(f"number of ids in older master DataFrame not in new DataFrame: {len(in_old_not_new)}")
print(f"number of ids in new DataFrame not in older master DataFrame: {len(in_new_not_old)}")
print(f"number of ids in MySQL not in DataFrame: {len(in_sql_not_old)}")
print(f"number of ids in old DataFrame not in MySQL: {len(in_old_not_sql)}")

Original length: 1942476
Unique length: 3853
Length of older master DataFrame: 1457107
IDs in MySQL not in DataFrame: {0, 1539, 246660, 200067, 212358, 213896, 234377, 177803, 245900, 155277, 242836, 223638, 177311, 236836, 233765, 225577, 166314, 146475, 208428, 215982, 560, 260656, 216243, 231992, 223800, 224570, 137403, 221884, 213436, 1088, 248389, 208838, 31432, 1099, 138699, 122361, 225486, 232016, 212728, 200787, 116308, 222038, 226266, 163419, 179708, 212826, 237279, 232033, 176993, 226405, 225254, 198760, 192369, 186100, 218868, 176376, 107769, 255740, 242301}
IDs in DataFrame not in MySQL: {77313, 251905, 79876, 271365, 79882, 79884, 79890, 79893, 248855, 81948, 79902, 245279, 278047, 273969, 79921, 84025, 84042, 224348, 242791, 83056, 83060, 273529, 279164, 79998, 77456, 73874, 73875, 81554, 77462, 84120, 76445, 84126, 77472, 271017, 83116, 77484, 77485, 77489, 77492, 265402, 70331, 83133, 237248, 77505, 231108, 77516, 83667, 80609, 276207, 83209, 83721, 271632, 252700, 83741, 227622, 219951, 83259, 75070, 232255, 83264, 234819, 248674, 84334, 247156, 78713, 254841, 78203, 78205, 83326, 84350, 78208, 78209, 78206, 84351, 82308, 83333, 83335, 75145, 83342, 83343, 83346, 83347, 83352, 83359, 83361, 83362, 83363, 261028, 83365, 252326, 81827, 83373, 83374, 78773, 79846, 275943, 79850, 83955, 79860, 79863, 257020}
IDs in older master DataFrame not in new DataFrame: set()
IDs in new DataFrame not in older master DataFrame: {77313, 251905, 79876, 271365, 79882, 79884, 79890, 79893, 248855, 81948, 79902, 245279, 278047, 273969, 79921, 84025, 84042, 224348, 242791, 83056, 83060, 273529, 279164, 79998, 77456, 73874, 73875, 81554, 77462, 84120, 76445, 84126, 77472, 271017, 83116, 77484, 77485, 77489, 77492, 265402, 70331, 83133, 237248, 77505, 231108, 77516, 83667, 80609, 276207, 83209, 83721, 271632, 252700, 83741, 227622, 219951, 83259, 75070, 232255, 83264, 234819, 248674, 84334, 247156, 78713, 254841, 78203, 78205, 83326, 84350, 78208, 78209, 78206, 84351, 82308, 83333, 83335, 75145, 83342, 83343, 83346, 83347, 83352, 83359, 83361, 83362, 83363, 261028, 83365, 252326, 81827, 83373, 83374, 78773, 79846, 275943, 79850, 83955, 79860, 79863, 257020}
IDs in MySQL not in DataFrame: {0, 1539, 246660, 200067, 212358, 213896, 234377, 177803, 245900, 155277, 242836, 223638, 177311, 236836, 233765, 225577, 166314, 146475, 208428, 215982, 560, 260656, 216243, 231992, 223800, 224570, 137403, 221884, 213436, 1088, 248389, 208838, 31432, 1099, 138699, 122361, 225486, 232016, 212728, 200787, 116308, 222038, 226266, 163419, 179708, 212826, 237279, 232033, 176993, 226405, 225254, 198760, 192369, 186100, 218868, 176376, 107769, 255740, 242301}
IDs in DataFrame not in MySQL: set()
number of ids in MySQL not in DataFrame: 59
number of ids in DataFrame not in MySQL: 101
number of ids in older master DataFrame not in new DataFrame: 0
number of ids in new DataFrame not in older master DataFrame: 101
number of ids in MySQL not in DataFrame: 59
number of ids in old DataFrame not in MySQL: 0