In [17]:
import pandas as pd
from sqlalchemy import create_engine
import os

db_string = 'mysql+pymysql://root:!wMoU9lBdLZWW6Y8@o8ukkP9TliImN.h.filess.io:58202/MLS'

engine = create_engine(db_string)

In [18]:
df = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/players/cleaned_master_players_w_team_abbr_post031426.csv')
df2 = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/players/cleaned_master_players_w_team_abbr_post031426_2.csv')

In [19]:
df = pd.concat([df, df2], ignore_index=True)

In [20]:
df

,id,date,name,age,height_cm,weight_kg,team_name,contract_start,contract_end,position,...,standing_tackle,sliding_tackle,total_goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,team_abbr,team_id
0,247228,2026-03-10,D. St. Clair,28.0,191,86,Inter Miami,NaN,NaN,NaN,...,10.0,12.0,350,73.0,69.0,60.0,72.0,76.0,MIA,NaN
1,262339,2026-03-10,G. Lujan,24.0,182,82,Inter Miami,NaN,NaN,NaN,...,69.0,68.0,43,10.0,9.0,5.0,9.0,10.0,MIA,NaN
2,259298,2026-03-10,M. Falcon,28.0,179,80,Inter Miami,NaN,NaN,NaN,...,67.0,64.0,52,7.0,11.0,15.0,11.0,8.0,MIA,NaN
3,260732,2026-03-10,I. Fray,22.0,183,73,Inter Miami,NaN,NaN,NaN,...,67.0,63.0,57,13.0,10.0,6.0,15.0,13.0,MIA,NaN
4,267872,2026-03-10,N. Allen,21.0,175,66,Inter Miami,NaN,NaN,NaN,...,68.0,66.0,52,11.0,13.0,9.0,8.0,11.0,MIA,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459242,233943,2025-12-02,Ronaldo Vieira,26.0,178,70,San Jose Earthquakes,NaN,NaN,NaN,...,68.0,65.0,43,12.0,10.0,7.0,6.0,8.0,SJ,111928.0
1459243,256110,2025-12-02,J. Skahan,27.0,178,78,San Jose Earthquakes,NaN,NaN,NaN,...,55.0,55.0,41,14.0,7.0,8.0,5.0,7.0,SJ,111928.0
1459244,73877,2025-12-02,J. Ricketts,23.0,175,75,San Jose Earthquakes,NaN,NaN,NaN,...,62.0,61.0,51,14.0,8.0,6.0,8.0,15.0,SJ,111928.0
1459245,77511,2025-12-02,R. Roberts,21.0,185,81,San Jose Earthquakes,NaN,NaN,NaN,...,54.0,53.0,50,7.0,9.0,11.0,11.0,12.0,SJ,111928.0
1459246,78210,2025-12-02,F. Montali,24.0,191,84,San Jose Earthquakes,NaN,NaN,NaN,...,12.0,13.0,268,58.0,54.0,51.0,51.0,54.0,SJ,111928.0

In [21]:
## delete name, height_cm, weight_kg, team, contract_start, contract_end, position, foot, wage_eur, value_eur from stats

df2 = df.drop(columns=['name', 'height_cm', 'weight_kg', 'team_name', 'team_abbr', 'contract_start', 'contract_end', 'position', 'foot', 'wage_eur', 'value_eur'])

## rename id to player_id
df2 = df2.rename(columns={'id': 'player_id'})

df2 = df2.rename(columns={'att._position': 'att_position'})

In [22]:
### check if all player_id and date combos are unique

if df2.duplicated(subset=['player_id', 'date']).any():
    print("There are duplicate player_id and date combinations.")

### see duplicate player_id and date combos

duplicates = df2[df2.duplicated(subset=['player_id', 'date'], keep=False)]
duplicates = duplicates.sort_values(by=['player_id', 'date'])
print(duplicates.head(10))

There are duplicate player_id and date combinations.
         player_id        date   age  jersey_num  overall_rating  \
391072         250  2007-08-30  32.0         NaN            81.0
874301         250  2007-08-30  32.0         NaN            81.0
1357530        250  2007-08-30  32.0         NaN            81.0
428847         250  2008-02-22  32.0         NaN            84.0
912076         250  2008-02-22  32.0         NaN            84.0
1395305        250  2008-02-22  32.0         NaN            84.0
428547         250  2008-08-30  33.0         NaN            78.0
911776         250  2008-08-30  33.0         NaN            78.0
1395005        250  2008-08-30  33.0         NaN            78.0
429517         250  2009-08-30  34.0         NaN            83.0

         best_overall best_position  total_attacking  crossing  finishing  \
391072             85            CF              293      95.0       68.0
874301             85            CF              293      95.0       68.0
1357530            85            CF              293      95.0       68.0
428847             85            CF              293      95.0       68.0
912076             85            CF              293      95.0       68.0
1395305            85            CF              293      95.0       68.0
428547             82            CF              290      95.0       68.0
911776             82            CF              290      95.0       68.0
1395005            82            CF              290      95.0       68.0
429517             83            CF              293      93.0       76.0

         ...  defensive_awareness  standing_tackle  sliding_tackle  \
391072   ...                  NaN              NaN             0.0
874301   ...                  NaN              NaN             0.0
1357530  ...                  NaN              NaN             0.0
428847   ...                  NaN              NaN             0.0
912076   ...                  NaN              NaN             0.0
1395305  ...                  NaN              NaN             0.0
428547   ...                  NaN              NaN             0.0
911776   ...                  NaN              NaN             0.0
1395005  ...                  NaN              NaN             0.0
429517   ...                  NaN              NaN             0.0

         total_goalkeeping  gk_diving  gk_handling  gk_kicking  \
391072                  74       11.0         31.0         0.0
874301                  74       11.0         31.0         0.0
1357530                 74       11.0         31.0         0.0
428847                  74       11.0         21.0         0.0
912076                  74       11.0         21.0         0.0
1395305                 74       11.0         21.0         0.0
428547                  74       11.0         21.0         0.0
911776                  74       11.0         21.0         0.0
1395005                 74       11.0         21.0         0.0
429517                  74       11.0         21.0         0.0

         gk_positioning  gk_reflexes  team_id
391072             37.0         30.0    697.0
874301             37.0         30.0    697.0
1357530            37.0         30.0    697.0
428847             21.0         21.0    697.0
912076             21.0         21.0    697.0
1395305            21.0         21.0    697.0
428547             21.0         21.0    697.0
911776             21.0         21.0    697.0
1395005            21.0         21.0    697.0
429517             21.0         21.0    697.0

[10 rows x 48 columns]

In [23]:
### delete one of the duplicates
df2 = df2.drop_duplicates(subset=['player_id', 'date'], keep='first')

In [24]:
df2.drop(columns=[ 'team_id'], inplace=True)

In [26]:
df2

,player_id,date,age,jersey_num,overall_rating,best_overall,best_position,total_attacking,crossing,finishing,...,total_defending,defensive_awareness,standing_tackle,sliding_tackle,total_goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,247228,2026-03-10,28.0,NaN,73.0,73,GK,52,14.0,5.0,...,30,8.0,10.0,12.0,350,73.0,69.0,60.0,72.0,76.0
1,262339,2026-03-10,24.0,NaN,68.0,70,CB,239,66.0,25.0,...,204,67.0,69.0,68.0,43,10.0,9.0,5.0,9.0,10.0
2,259298,2026-03-10,28.0,NaN,69.0,69,CB,201,25.0,33.0,...,193,62.0,67.0,64.0,52,7.0,11.0,15.0,11.0,8.0
3,260732,2026-03-10,22.0,NaN,65.0,66,CB,240,58.0,42.0,...,196,66.0,67.0,63.0,57,13.0,10.0,6.0,15.0,13.0
4,267872,2026-03-10,21.0,NaN,66.0,68,CB,253,64.0,29.0,...,198,64.0,68.0,66.0,52,11.0,13.0,9.0,8.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459242,233943,2025-12-02,26.0,NaN,68.0,69,CDM,283,56.0,53.0,...,199,66.0,68.0,65.0,43,12.0,10.0,7.0,6.0,8.0
1459243,256110,2025-12-02,27.0,NaN,62.0,63,CAM,249,47.0,45.0,...,155,45.0,55.0,55.0,41,14.0,7.0,8.0,5.0,7.0
1459244,73877,2025-12-02,23.0,NaN,59.0,61,LWB,252,59.0,48.0,...,175,52.0,62.0,61.0,51,14.0,8.0,6.0,8.0,15.0
1459245,77511,2025-12-02,21.0,NaN,57.0,59,CB,185,20.0,16.0,...,167,60.0,54.0,53.0,50,7.0,9.0,11.0,11.0,12.0
1459246,78210,2025-12-02,24.0,NaN,55.0,55,GK,66,14.0,7.0,...,34,9.0,12.0,13.0,268,58.0,54.0,51.0,51.0,54.0

In [25]:
from sqlalchemy import Table, MetaData, insert


metadata = MetaData()
metadata.reflect(bind=engine)

# Access any table like a dictionary
players_table = metadata.tables['players_stats']

stmt = insert(players_table).prefix_with("IGNORE").values(df2)

In [27]:
df2.to_sql('players_stats', con=engine, if_exists='append', index=False)

492777

In [10]:
df3 = df[['id', 'date', 'wage_eur', 'value_eur']]

df3 = df3.rename(columns={'id': 'player_id'})

In [12]:
df3

         player_id        date  wage_eur  value_eur
0           247228  2026-03-10      5000    2800000
1           262339  2026-03-10      4000    1700000
2           259298  2026-03-10      5000    1200000
3           260732  2026-03-10      2000    1500000
4           267872  2026-03-10      2000    1800000
...            ...         ...       ...        ...
1459242     233943  2025-12-02      4000   13000000
1459243     256110  2025-12-02      2000     450000
1459244      73877  2025-12-02      1000     350000
1459245      77511  2025-12-02      1000     350000
1459246      78210  2025-12-02       500     140000

[1459247 rows x 4 columns]

In [13]:
if df3.duplicated(subset=['player_id', 'date']).any():
    print("There are duplicate player_id and date combinations.")

### see duplicate player_id and date combos

duplicates2 = df3[df3.duplicated(subset=['player_id', 'date'], keep=False)]
duplicates2 = duplicates2.sort_values(by=['player_id', 'date'])
print(duplicates2.head(10))

There are duplicate player_id and date combinations.
         player_id        date  wage_eur  value_eur
391072         250  2007-08-30         0          0
874301         250  2007-08-30         0          0
1357530        250  2007-08-30         0          0
428847         250  2008-02-22         0          0
912076         250  2008-02-22         0          0
1395305        250  2008-02-22         0          0
428547         250  2008-08-30         0          0
911776         250  2008-08-30         0          0
1395005        250  2008-08-30         0          0
429517         250  2009-08-30         0          0

In [14]:
df3 = df3.drop_duplicates(subset=['player_id', 'date'], keep='first')

In [16]:
from sqlalchemy import Table, MetaData, insert


metadata = MetaData()
metadata.reflect(bind=engine)

# Access any table like a dictionary
players_table = metadata.tables['player_finance']

stmt = insert(players_table).prefix_with("IGNORE").values(df3)

In [ ]:
df3.to_sql('players_finance', con=engine, if_exists='append', index=False)