In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
df = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/teams/master_teams_0326.csv')

In [3]:
df

,team_id,team_name,overall_score,attack,midfield,defense,worth_euro,num_players,lineup,style,date
0,111140,Portland Timbers,71,73,71,70,351.0,27,4-2-3-1,Wide,2021-10-14
1,111144,Seattle Sounders FC,71,72,71,68,364.5,28,5-3-2,NaN,2021-10-14
2,687,Columbus Crew,71,71,71,70,180.0,30,4-2-3-1,Wide,2021-10-14
3,112606,Orlando City SC,71,70,72,69,265.5,30,4-2-3-1,Wide,2021-10-14
4,112893,Inter Miami,71,80,71,68,330.0,28,4-2-3-1,Wide,2021-10-14
...,...,...,...,...,...,...,...,...,...,...,...
19090,111139,CF Montréal,66,70,65,64,189.0,27,4-2-3-1,Wide,2026-03-10
19091,111651,Toronto FC,66,61,69,65,218.5,22,4-2-3-1,Wide,2026-03-10
19092,689,New York Red Bulls,66,71,67,64,261.0,26,4-2-3-1,Wide,2026-03-10
19093,111928,San Jose Earthquakes,65,64,66,63,162.8,24,3-4-3,Flat,2026-03-10
19094,696,Sporting Kansas City,61,67,63,58,182.5,19,4-2-3-1,Wide,2026-03-10

In [4]:
team_name_to_id = dict(zip(df['team_name'], df['team_id']))

In [5]:
df = df[['team_id', 'team_name']]

teams_dict = {
    'Inter Miami': 'MIA',
    'Seattle Sounders FC': 'SEA',
    'Los Angeles FC': 'LAFC',
    'LA Galaxy': 'LA',
    'St. Louis CITY SC': 'STL',
    'Charlotte FC': 'CLT',
    'Atlanta United': 'ATL',
    'FC Cincinnati': 'CIN',
    'Portland Timbers': 'POR',
    'San Jose Earthquakes': 'SJ',
    'Columbus Crew': 'CLB',
    'New York Red Bulls': 'RBNY',
    'New England Revolution': 'NE',
    'Houston Dynamo': 'HOU',
    'Orlando City SC': 'ORL',
    'Austin FC': 'ATX',
    'Nashville SC': 'NSH',
    'Vancouver Whitecaps FC': 'VAN',
    'Philadelphia Union': 'PHI',
    'Minnesota United FC': 'MIN',
    'Toronto FC': 'TOR',
    'Chicago Fire': 'CHI',
    'FC Dallas': 'DAL',
    'Sporting Kansas City': 'SKC',
    'Real Salt Lake': 'RSL',
    'DC United': 'DC',
    'Colorado Rapids': 'COL',
    'New York City FC': 'NYC',
    'CF Montréal': 'MTL',
    'San Diego FC': 'SD',
}

In [6]:
df['team_abbr'] = df['team_name'].map(teams_dict)

C:\Users\diffe\AppData\Local\Temp\ipykernel_8884\2601928823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['team_abbr'] = df['team_name'].map(teams_dict)

In [7]:
df

       team_id             team_name team_abbr
0       111140      Portland Timbers       POR
1       111144   Seattle Sounders FC       SEA
2          687         Columbus Crew       CLB
3       112606       Orlando City SC       ORL
4       112893           Inter Miami       MIA
...        ...                   ...       ...
19090   111139           CF Montréal       MTL
19091   111651            Toronto FC       TOR
19092      689    New York Red Bulls      RBNY
19093   111928  San Jose Earthquakes        SJ
19094      696  Sporting Kansas City       SKC

[19095 rows x 3 columns]

In [8]:
### remove duplicates if any

df = df.drop_duplicates(subset=['team_id'])

In [9]:
df

       team_id               team_name team_abbr
0       111140        Portland Timbers       POR
1       111144     Seattle Sounders FC       SEA
2          687           Columbus Crew       CLB
3       112606         Orlando City SC       ORL
4       112893             Inter Miami       MIA
5       112134      Philadelphia Union       PHI
6       111138     Minnesota United FC       MIN
7          688               DC United        DC
8          691  New England Revolution        NE
9          696    Sporting Kansas City       SKC
10      112828        New York City FC       NYC
11      112885          Atlanta United       ATL
12      111651              Toronto FC       TOR
13      112996          Los Angeles FC      LAFC
14         694         Colorado Rapids       COL
15         695               FC Dallas       DAL
16         697               LA Galaxy        LA
17      114162            Nashville SC       NSH
18      111139             CF Montréal       MTL
19      111928    San Jose Earthquakes        SJ
20         689      New York Red Bulls      RBNY
21         693            Chicago Fire       CHI
22         698          Houston Dynamo       HOU
23      111065          Real Salt Lake       RSL
24      114161               Austin FC       ATX
25      101112  Vancouver Whitecaps FC       VAN
26      113149           FC Cincinnati       CIN
125     111070              Chivas USA       NaN
1975    114640            Charlotte FC       CLT
2004    113018       St. Louis CITY SC       STL
17948   131439            San Diego FC        SD

In [10]:
db_string = 'mysql+pymysql://root:!wMoU9lBdLZWW6Y8@o8ukkP9TliImN.h.filess.io:58202/MLS'

engine = create_engine(db_string)

In [11]:
df.to_sql('teams', engine, if_exists='append', index=False)

31